[package]
name = "icobasic"
version = "0.1.0"
edition = "2024"

[dependencies]

[features]
default = ["x86_64-linux-c99", "x86_64-win32-c99"]
x86_64-linux-c99 = []
x86_64-win32-c99 = []
i686-linux-c99 = []
i686-win32-c99 = []
